/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ShellnutsFooter {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface ShellnutsHeader {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLShellnutsFooterElement extends Components.ShellnutsFooter, HTMLStencilElement {
    }
    var HTMLShellnutsFooterElement: {
        prototype: HTMLShellnutsFooterElement;
        new (): HTMLShellnutsFooterElement;
    };
    interface HTMLShellnutsHeaderElement extends Components.ShellnutsHeader, HTMLStencilElement {
    }
    var HTMLShellnutsHeaderElement: {
        prototype: HTMLShellnutsHeaderElement;
        new (): HTMLShellnutsHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "shellnuts-footer": HTMLShellnutsFooterElement;
        "shellnuts-header": HTMLShellnutsHeaderElement;
    }
}
declare namespace LocalJSX {
    interface ShellnutsFooter {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface ShellnutsHeader {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "shellnuts-footer": ShellnutsFooter;
        "shellnuts-header": ShellnutsHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "shellnuts-footer": LocalJSX.ShellnutsFooter & JSXBase.HTMLAttributes<HTMLShellnutsFooterElement>;
            "shellnuts-header": LocalJSX.ShellnutsHeader & JSXBase.HTMLAttributes<HTMLShellnutsHeaderElement>;
        }
    }
}
